name: finapp
description: finapp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
